//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace OnTheSpot.EFStuff
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AssemblyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AssemblyEntities object using the connection string found in the 'AssemblyEntities' section of the application configuration file.
        /// </summary>
        public AssemblyEntities() : base("name=AssemblyEntities", "AssemblyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssemblyEntities object.
        /// </summary>
        public AssemblyEntities(string connectionString) : base(connectionString, "AssemblyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssemblyEntities object.
        /// </summary>
        public AssemblyEntities(EntityConnection connection) : base(connection, "AssemblyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Invoice> Invoices
        {
            get
            {
                if ((_Invoices == null))
                {
                    _Invoices = base.CreateObjectSet<Invoice>("Invoices");
                }
                return _Invoices;
            }
        }
        private ObjectSet<Invoice> _Invoices;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AutoSort> AutoSorts
        {
            get
            {
                if ((_AutoSorts == null))
                {
                    _AutoSorts = base.CreateObjectSet<AutoSort>("AutoSorts");
                }
                return _AutoSorts;
            }
        }
        private ObjectSet<AutoSort> _AutoSorts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Invoices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInvoices(Invoice invoice)
        {
            base.AddObject("Invoices", invoice);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AutoSorts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAutoSorts(AutoSort autoSort)
        {
            base.AddObject("AutoSorts", autoSort);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AssemblyModel", Name="AutoSort")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AutoSort : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AutoSort object.
        /// </summary>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        /// <param name="storeID">Initial value of the StoreID property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="queue">Initial value of the Queue property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="remaining">Initial value of the Remaining property.</param>
        /// <param name="baySection">Initial value of the BaySection property.</param>
        /// <param name="useBAMStorage">Initial value of the UseBAMStorage property.</param>
        /// <param name="subOut">Initial value of the SubOut property.</param>
        public static AutoSort CreateAutoSort(global::System.Int32 invoiceID, global::System.Int32 storeID, global::System.Int32 customerID, global::System.Int32 queue, global::System.Int32 state, global::System.Int32 remaining, global::System.Int32 baySection, global::System.Boolean useBAMStorage, global::System.Int32 subOut)
        {
            AutoSort autoSort = new AutoSort();
            autoSort.InvoiceID = invoiceID;
            autoSort.StoreID = storeID;
            autoSort.CustomerID = customerID;
            autoSort.Queue = queue;
            autoSort.State = state;
            autoSort.Remaining = remaining;
            autoSort.BaySection = baySection;
            autoSort.UseBAMStorage = useBAMStorage;
            autoSort.SubOut = subOut;
            return autoSort;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                if (_InvoiceID != value)
                {
                    OnInvoiceIDChanging(value);
                    ReportPropertyChanging("InvoiceID");
                    _InvoiceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InvoiceID");
                    OnInvoiceIDChanged();
                }
            }
        }
        private global::System.Int32 _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.Int32 value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreID
        {
            get
            {
                return _StoreID;
            }
            set
            {
                if (_StoreID != value)
                {
                    OnStoreIDChanging(value);
                    ReportPropertyChanging("StoreID");
                    _StoreID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StoreID");
                    OnStoreIDChanged();
                }
            }
        }
        private global::System.Int32 _StoreID;
        partial void OnStoreIDChanging(global::System.Int32 value);
        partial void OnStoreIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StoreInvoiceID
        {
            get
            {
                return _StoreInvoiceID;
            }
            set
            {
                OnStoreInvoiceIDChanging(value);
                ReportPropertyChanging("StoreInvoiceID");
                _StoreInvoiceID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StoreInvoiceID");
                OnStoreInvoiceIDChanged();
            }
        }
        private global::System.String _StoreInvoiceID;
        partial void OnStoreInvoiceIDChanging(global::System.String value);
        partial void OnStoreInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PieceTotal
        {
            get
            {
                return _PieceTotal;
            }
            set
            {
                OnPieceTotalChanging(value);
                ReportPropertyChanging("PieceTotal");
                _PieceTotal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PieceTotal");
                OnPieceTotalChanged();
            }
        }
        private global::System.String _PieceTotal;
        partial void OnPieceTotalChanging(global::System.String value);
        partial void OnPieceTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemNumber
        {
            get
            {
                return _ItemNumber;
            }
            set
            {
                OnItemNumberChanging(value);
                ReportPropertyChanging("ItemNumber");
                _ItemNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemNumber");
                OnItemNumberChanged();
            }
        }
        private global::System.String _ItemNumber;
        partial void OnItemNumberChanging(global::System.String value);
        partial void OnItemNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArticleCode
        {
            get
            {
                return _ArticleCode;
            }
            set
            {
                OnArticleCodeChanging(value);
                ReportPropertyChanging("ArticleCode");
                _ArticleCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArticleCode");
                OnArticleCodeChanged();
            }
        }
        private global::System.String _ArticleCode;
        partial void OnArticleCodeChanging(global::System.String value);
        partial void OnArticleCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OccPercent
        {
            get
            {
                return _OccPercent;
            }
            set
            {
                OnOccPercentChanging(value);
                ReportPropertyChanging("OccPercent");
                _OccPercent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OccPercent");
                OnOccPercentChanged();
            }
        }
        private global::System.String _OccPercent;
        partial void OnOccPercentChanging(global::System.String value);
        partial void OnOccPercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hung
        {
            get
            {
                return _Hung;
            }
            set
            {
                OnHungChanging(value);
                ReportPropertyChanging("Hung");
                _Hung = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hung");
                OnHungChanged();
            }
        }
        private global::System.String _Hung;
        partial void OnHungChanging(global::System.String value);
        partial void OnHungChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Conveyor
        {
            get
            {
                return _Conveyor;
            }
            set
            {
                OnConveyorChanging(value);
                ReportPropertyChanging("Conveyor");
                _Conveyor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Conveyor");
                OnConveyorChanged();
            }
        }
        private global::System.String _Conveyor;
        partial void OnConveyorChanging(global::System.String value);
        partial void OnConveyorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Slot
        {
            get
            {
                return _Slot;
            }
            set
            {
                OnSlotChanging(value);
                ReportPropertyChanging("Slot");
                _Slot = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Slot");
                OnSlotChanged();
            }
        }
        private global::System.String _Slot;
        partial void OnSlotChanging(global::System.String value);
        partial void OnSlotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Out
        {
            get
            {
                return _Out;
            }
            set
            {
                OnOutChanging(value);
                ReportPropertyChanging("Out");
                _Out = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Out");
                OnOutChanged();
            }
        }
        private global::System.String _Out;
        partial void OnOutChanging(global::System.String value);
        partial void OnOutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Customer
        {
            get
            {
                return _Customer;
            }
            set
            {
                OnCustomerChanging(value);
                ReportPropertyChanging("Customer");
                _Customer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Customer");
                OnCustomerChanged();
            }
        }
        private global::System.String _Customer;
        partial void OnCustomerChanging(global::System.String value);
        partial void OnCustomerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RFID
        {
            get
            {
                return _RFID;
            }
            set
            {
                OnRFIDChanging(value);
                ReportPropertyChanging("RFID");
                _RFID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RFID");
                OnRFIDChanged();
            }
        }
        private global::System.String _RFID;
        partial void OnRFIDChanging(global::System.String value);
        partial void OnRFIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Arm
        {
            get
            {
                return _Arm;
            }
            set
            {
                OnArmChanging(value);
                ReportPropertyChanging("Arm");
                _Arm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Arm");
                OnArmChanged();
            }
        }
        private global::System.String _Arm;
        partial void OnArmChanging(global::System.String value);
        partial void OnArmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Queue
        {
            get
            {
                return _Queue;
            }
            set
            {
                if (_Queue != value)
                {
                    OnQueueChanging(value);
                    ReportPropertyChanging("Queue");
                    _Queue = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Queue");
                    OnQueueChanged();
                }
            }
        }
        private global::System.Int32 _Queue;
        partial void OnQueueChanging(global::System.Int32 value);
        partial void OnQueueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 State
        {
            get
            {
                return _State;
            }
            set
            {
                if (_State != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _State = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }
        private global::System.Int32 _State;
        partial void OnStateChanging(global::System.Int32 value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Remaining
        {
            get
            {
                return _Remaining;
            }
            set
            {
                if (_Remaining != value)
                {
                    OnRemainingChanging(value);
                    ReportPropertyChanging("Remaining");
                    _Remaining = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Remaining");
                    OnRemainingChanged();
                }
            }
        }
        private global::System.Int32 _Remaining;
        partial void OnRemainingChanging(global::System.Int32 value);
        partial void OnRemainingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InvoiceDate
        {
            get
            {
                return _InvoiceDate;
            }
            set
            {
                OnInvoiceDateChanging(value);
                ReportPropertyChanging("InvoiceDate");
                _InvoiceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceDate");
                OnInvoiceDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _InvoiceDate;
        partial void OnInvoiceDateChanging(Nullable<global::System.DateTime> value);
        partial void OnInvoiceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DueDate;
        partial void OnDueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomePhone
        {
            get
            {
                return _HomePhone;
            }
            set
            {
                OnHomePhoneChanging(value);
                ReportPropertyChanging("HomePhone");
                _HomePhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomePhone");
                OnHomePhoneChanged();
            }
        }
        private global::System.String _HomePhone;
        partial void OnHomePhoneChanging(global::System.String value);
        partial void OnHomePhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BaySection
        {
            get
            {
                return _BaySection;
            }
            set
            {
                if (_BaySection != value)
                {
                    OnBaySectionChanging(value);
                    ReportPropertyChanging("BaySection");
                    _BaySection = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BaySection");
                    OnBaySectionChanged();
                }
            }
        }
        private global::System.Int32 _BaySection;
        partial void OnBaySectionChanging(global::System.Int32 value);
        partial void OnBaySectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BagLabel1
        {
            get
            {
                return _BagLabel1;
            }
            set
            {
                OnBagLabel1Changing(value);
                ReportPropertyChanging("BagLabel1");
                _BagLabel1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BagLabel1");
                OnBagLabel1Changed();
            }
        }
        private global::System.String _BagLabel1;
        partial void OnBagLabel1Changing(global::System.String value);
        partial void OnBagLabel1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BagLabel2
        {
            get
            {
                return _BagLabel2;
            }
            set
            {
                OnBagLabel2Changing(value);
                ReportPropertyChanging("BagLabel2");
                _BagLabel2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BagLabel2");
                OnBagLabel2Changed();
            }
        }
        private global::System.String _BagLabel2;
        partial void OnBagLabel2Changing(global::System.String value);
        partial void OnBagLabel2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BagLabel3
        {
            get
            {
                return _BagLabel3;
            }
            set
            {
                OnBagLabel3Changing(value);
                ReportPropertyChanging("BagLabel3");
                _BagLabel3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BagLabel3");
                OnBagLabel3Changed();
            }
        }
        private global::System.String _BagLabel3;
        partial void OnBagLabel3Changing(global::System.String value);
        partial void OnBagLabel3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BagLabel4
        {
            get
            {
                return _BagLabel4;
            }
            set
            {
                OnBagLabel4Changing(value);
                ReportPropertyChanging("BagLabel4");
                _BagLabel4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BagLabel4");
                OnBagLabel4Changed();
            }
        }
        private global::System.String _BagLabel4;
        partial void OnBagLabel4Changing(global::System.String value);
        partial void OnBagLabel4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BagLabel5
        {
            get
            {
                return _BagLabel5;
            }
            set
            {
                OnBagLabel5Changing(value);
                ReportPropertyChanging("BagLabel5");
                _BagLabel5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BagLabel5");
                OnBagLabel5Changed();
            }
        }
        private global::System.String _BagLabel5;
        partial void OnBagLabel5Changing(global::System.String value);
        partial void OnBagLabel5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BagLabel6
        {
            get
            {
                return _BagLabel6;
            }
            set
            {
                OnBagLabel6Changing(value);
                ReportPropertyChanging("BagLabel6");
                _BagLabel6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BagLabel6");
                OnBagLabel6Changed();
            }
        }
        private global::System.String _BagLabel6;
        partial void OnBagLabel6Changing(global::System.String value);
        partial void OnBagLabel6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean UseBAMStorage
        {
            get
            {
                return _UseBAMStorage;
            }
            set
            {
                if (_UseBAMStorage != value)
                {
                    OnUseBAMStorageChanging(value);
                    ReportPropertyChanging("UseBAMStorage");
                    _UseBAMStorage = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UseBAMStorage");
                    OnUseBAMStorageChanged();
                }
            }
        }
        private global::System.Boolean _UseBAMStorage;
        partial void OnUseBAMStorageChanging(global::System.Boolean value);
        partial void OnUseBAMStorageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubOut
        {
            get
            {
                return _SubOut;
            }
            set
            {
                if (_SubOut != value)
                {
                    OnSubOutChanging(value);
                    ReportPropertyChanging("SubOut");
                    _SubOut = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubOut");
                    OnSubOutChanged();
                }
            }
        }
        private global::System.Int32 _SubOut;
        partial void OnSubOutChanging(global::System.Int32 value);
        partial void OnSubOutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FlagTag
        {
            get
            {
                return _FlagTag;
            }
            set
            {
                OnFlagTagChanging(value);
                ReportPropertyChanging("FlagTag");
                _FlagTag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FlagTag");
                OnFlagTagChanged();
            }
        }
        private global::System.String _FlagTag;
        partial void OnFlagTagChanging(global::System.String value);
        partial void OnFlagTagChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AssemblyModel", Name="Invoice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Invoice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Invoice object.
        /// </summary>
        /// <param name="invoiceID">Initial value of the InvoiceID property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="storeID">Initial value of the StoreID property.</param>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="departmentID">Initial value of the DepartmentID property.</param>
        /// <param name="invoiceEmpID">Initial value of the InvoiceEmpID property.</param>
        /// <param name="rackEmpID">Initial value of the RackEmpID property.</param>
        /// <param name="pickupEmpID">Initial value of the PickupEmpID property.</param>
        /// <param name="isMissingAmount">Initial value of the IsMissingAmount property.</param>
        /// <param name="workPhase">Initial value of the WorkPhase property.</param>
        /// <param name="pieces">Initial value of the Pieces property.</param>
        /// <param name="tax1ID">Initial value of the Tax1ID property.</param>
        /// <param name="taxable">Initial value of the Taxable property.</param>
        /// <param name="taxTotal">Initial value of the TaxTotal property.</param>
        /// <param name="subTotal">Initial value of the SubTotal property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        /// <param name="paidAmount">Initial value of the PaidAmount property.</param>
        /// <param name="paymentID">Initial value of the PaymentID property.</param>
        /// <param name="coupTotal">Initial value of the CoupTotal property.</param>
        /// <param name="discTotal">Initial value of the DiscTotal property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        /// <param name="coupDiscable">Initial value of the CoupDiscable property.</param>
        /// <param name="srvFeeable">Initial value of the SrvFeeable property.</param>
        /// <param name="srvFeeTotal">Initial value of the SrvFeeTotal property.</param>
        /// <param name="valetTicketID">Initial value of the ValetTicketID property.</param>
        /// <param name="billCustomerID">Initial value of the BillCustomerID property.</param>
        /// <param name="tax2ID">Initial value of the Tax2ID property.</param>
        /// <param name="tax3ID">Initial value of the Tax3ID property.</param>
        /// <param name="taxable1">Initial value of the Taxable1 property.</param>
        /// <param name="taxable2">Initial value of the Taxable2 property.</param>
        /// <param name="taxable3">Initial value of the Taxable3 property.</param>
        /// <param name="taxTotal1">Initial value of the TaxTotal1 property.</param>
        /// <param name="taxTotal2">Initial value of the TaxTotal2 property.</param>
        /// <param name="taxTotal3">Initial value of the TaxTotal3 property.</param>
        /// <param name="originalTotal">Initial value of the OriginalTotal property.</param>
        /// <param name="isRedo">Initial value of the IsRedo property.</param>
        /// <param name="isSplit">Initial value of the IsSplit property.</param>
        /// <param name="taxAuthorityID">Initial value of the TaxAuthorityID property.</param>
        /// <param name="payCode">Initial value of the PayCode property.</param>
        /// <param name="markInEmpID">Initial value of the MarkInEmpID property.</param>
        public static Invoice CreateInvoice(global::System.Int32 invoiceID, global::System.Int32 orderID, global::System.Int32 storeID, global::System.Int32 customerID, global::System.Int32 departmentID, global::System.Int32 invoiceEmpID, global::System.Int32 rackEmpID, global::System.Int32 pickupEmpID, global::System.Boolean isMissingAmount, global::System.Int32 workPhase, global::System.Single pieces, global::System.Int32 tax1ID, global::System.Decimal taxable, global::System.Decimal taxTotal, global::System.Decimal subTotal, global::System.Decimal total, global::System.Decimal paidAmount, global::System.Int32 paymentID, global::System.Decimal coupTotal, global::System.Decimal discTotal, global::System.Boolean deleted, global::System.Decimal coupDiscable, global::System.Decimal srvFeeable, global::System.Decimal srvFeeTotal, global::System.Int32 valetTicketID, global::System.Int32 billCustomerID, global::System.Int32 tax2ID, global::System.Int32 tax3ID, global::System.Decimal taxable1, global::System.Decimal taxable2, global::System.Decimal taxable3, global::System.Decimal taxTotal1, global::System.Decimal taxTotal2, global::System.Decimal taxTotal3, global::System.Decimal originalTotal, global::System.Boolean isRedo, global::System.Boolean isSplit, global::System.Int32 taxAuthorityID, global::System.Int32 payCode, global::System.Int32 markInEmpID)
        {
            Invoice invoice = new Invoice();
            invoice.InvoiceID = invoiceID;
            invoice.OrderID = orderID;
            invoice.StoreID = storeID;
            invoice.CustomerID = customerID;
            invoice.DepartmentID = departmentID;
            invoice.InvoiceEmpID = invoiceEmpID;
            invoice.RackEmpID = rackEmpID;
            invoice.PickupEmpID = pickupEmpID;
            invoice.IsMissingAmount = isMissingAmount;
            invoice.WorkPhase = workPhase;
            invoice.Pieces = pieces;
            invoice.Tax1ID = tax1ID;
            invoice.Taxable = taxable;
            invoice.TaxTotal = taxTotal;
            invoice.SubTotal = subTotal;
            invoice.Total = total;
            invoice.PaidAmount = paidAmount;
            invoice.PaymentID = paymentID;
            invoice.CoupTotal = coupTotal;
            invoice.DiscTotal = discTotal;
            invoice.Deleted = deleted;
            invoice.CoupDiscable = coupDiscable;
            invoice.SrvFeeable = srvFeeable;
            invoice.SrvFeeTotal = srvFeeTotal;
            invoice.ValetTicketID = valetTicketID;
            invoice.BillCustomerID = billCustomerID;
            invoice.Tax2ID = tax2ID;
            invoice.Tax3ID = tax3ID;
            invoice.Taxable1 = taxable1;
            invoice.Taxable2 = taxable2;
            invoice.Taxable3 = taxable3;
            invoice.TaxTotal1 = taxTotal1;
            invoice.TaxTotal2 = taxTotal2;
            invoice.TaxTotal3 = taxTotal3;
            invoice.OriginalTotal = originalTotal;
            invoice.IsRedo = isRedo;
            invoice.IsSplit = isSplit;
            invoice.TaxAuthorityID = taxAuthorityID;
            invoice.PayCode = payCode;
            invoice.MarkInEmpID = markInEmpID;
            return invoice;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceID
        {
            get
            {
                return _InvoiceID;
            }
            set
            {
                if (_InvoiceID != value)
                {
                    OnInvoiceIDChanging(value);
                    ReportPropertyChanging("InvoiceID");
                    _InvoiceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InvoiceID");
                    OnInvoiceIDChanged();
                }
            }
        }
        private global::System.Int32 _InvoiceID;
        partial void OnInvoiceIDChanging(global::System.Int32 value);
        partial void OnInvoiceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StoreID
        {
            get
            {
                return _StoreID;
            }
            set
            {
                if (_StoreID != value)
                {
                    OnStoreIDChanging(value);
                    ReportPropertyChanging("StoreID");
                    _StoreID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StoreID");
                    OnStoreIDChanged();
                }
            }
        }
        private global::System.Int32 _StoreID;
        partial void OnStoreIDChanging(global::System.Int32 value);
        partial void OnStoreIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                if (_DepartmentID != value)
                {
                    OnDepartmentIDChanging(value);
                    ReportPropertyChanging("DepartmentID");
                    _DepartmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentID");
                    OnDepartmentIDChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Department
        {
            get
            {
                return _Department;
            }
            set
            {
                OnDepartmentChanging(value);
                ReportPropertyChanging("Department");
                _Department = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Department");
                OnDepartmentChanged();
            }
        }
        private global::System.String _Department;
        partial void OnDepartmentChanging(global::System.String value);
        partial void OnDepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rack
        {
            get
            {
                return _Rack;
            }
            set
            {
                OnRackChanging(value);
                ReportPropertyChanging("Rack");
                _Rack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rack");
                OnRackChanged();
            }
        }
        private global::System.String _Rack;
        partial void OnRackChanging(global::System.String value);
        partial void OnRackChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LotInfo
        {
            get
            {
                return _LotInfo;
            }
            set
            {
                OnLotInfoChanging(value);
                ReportPropertyChanging("LotInfo");
                _LotInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LotInfo");
                OnLotInfoChanged();
            }
        }
        private global::System.String _LotInfo;
        partial void OnLotInfoChanging(global::System.String value);
        partial void OnLotInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InvoiceEmpID
        {
            get
            {
                return _InvoiceEmpID;
            }
            set
            {
                if (_InvoiceEmpID != value)
                {
                    OnInvoiceEmpIDChanging(value);
                    ReportPropertyChanging("InvoiceEmpID");
                    _InvoiceEmpID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InvoiceEmpID");
                    OnInvoiceEmpIDChanged();
                }
            }
        }
        private global::System.Int32 _InvoiceEmpID;
        partial void OnInvoiceEmpIDChanging(global::System.Int32 value);
        partial void OnInvoiceEmpIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RackEmpID
        {
            get
            {
                return _RackEmpID;
            }
            set
            {
                if (_RackEmpID != value)
                {
                    OnRackEmpIDChanging(value);
                    ReportPropertyChanging("RackEmpID");
                    _RackEmpID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RackEmpID");
                    OnRackEmpIDChanged();
                }
            }
        }
        private global::System.Int32 _RackEmpID;
        partial void OnRackEmpIDChanging(global::System.Int32 value);
        partial void OnRackEmpIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PickupEmpID
        {
            get
            {
                return _PickupEmpID;
            }
            set
            {
                if (_PickupEmpID != value)
                {
                    OnPickupEmpIDChanging(value);
                    ReportPropertyChanging("PickupEmpID");
                    _PickupEmpID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PickupEmpID");
                    OnPickupEmpIDChanged();
                }
            }
        }
        private global::System.Int32 _PickupEmpID;
        partial void OnPickupEmpIDChanging(global::System.Int32 value);
        partial void OnPickupEmpIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> InvoiceDate
        {
            get
            {
                return _InvoiceDate;
            }
            set
            {
                OnInvoiceDateChanging(value);
                ReportPropertyChanging("InvoiceDate");
                _InvoiceDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InvoiceDate");
                OnInvoiceDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _InvoiceDate;
        partial void OnInvoiceDateChanging(Nullable<global::System.DateTime> value);
        partial void OnInvoiceDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                OnDueDateChanging(value);
                ReportPropertyChanging("DueDate");
                _DueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DueDate");
                OnDueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DueDate;
        partial void OnDueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RackDate
        {
            get
            {
                return _RackDate;
            }
            set
            {
                OnRackDateChanging(value);
                ReportPropertyChanging("RackDate");
                _RackDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RackDate");
                OnRackDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RackDate;
        partial void OnRackDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRackDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PickupDate
        {
            get
            {
                return _PickupDate;
            }
            set
            {
                OnPickupDateChanging(value);
                ReportPropertyChanging("PickupDate");
                _PickupDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PickupDate");
                OnPickupDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PickupDate;
        partial void OnPickupDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPickupDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMissingAmount
        {
            get
            {
                return _IsMissingAmount;
            }
            set
            {
                if (_IsMissingAmount != value)
                {
                    OnIsMissingAmountChanging(value);
                    ReportPropertyChanging("IsMissingAmount");
                    _IsMissingAmount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsMissingAmount");
                    OnIsMissingAmountChanged();
                }
            }
        }
        private global::System.Boolean _IsMissingAmount;
        partial void OnIsMissingAmountChanging(global::System.Boolean value);
        partial void OnIsMissingAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkPhase
        {
            get
            {
                return _WorkPhase;
            }
            set
            {
                if (_WorkPhase != value)
                {
                    OnWorkPhaseChanging(value);
                    ReportPropertyChanging("WorkPhase");
                    _WorkPhase = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WorkPhase");
                    OnWorkPhaseChanged();
                }
            }
        }
        private global::System.Int32 _WorkPhase;
        partial void OnWorkPhaseChanging(global::System.Int32 value);
        partial void OnWorkPhaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single Pieces
        {
            get
            {
                return _Pieces;
            }
            set
            {
                if (_Pieces != value)
                {
                    OnPiecesChanging(value);
                    ReportPropertyChanging("Pieces");
                    _Pieces = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Pieces");
                    OnPiecesChanged();
                }
            }
        }
        private global::System.Single _Pieces;
        partial void OnPiecesChanging(global::System.Single value);
        partial void OnPiecesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tax1ID
        {
            get
            {
                return _Tax1ID;
            }
            set
            {
                if (_Tax1ID != value)
                {
                    OnTax1IDChanging(value);
                    ReportPropertyChanging("Tax1ID");
                    _Tax1ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Tax1ID");
                    OnTax1IDChanged();
                }
            }
        }
        private global::System.Int32 _Tax1ID;
        partial void OnTax1IDChanging(global::System.Int32 value);
        partial void OnTax1IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Taxable
        {
            get
            {
                return _Taxable;
            }
            set
            {
                if (_Taxable != value)
                {
                    OnTaxableChanging(value);
                    ReportPropertyChanging("Taxable");
                    _Taxable = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Taxable");
                    OnTaxableChanged();
                }
            }
        }
        private global::System.Decimal _Taxable;
        partial void OnTaxableChanging(global::System.Decimal value);
        partial void OnTaxableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TaxTotal
        {
            get
            {
                return _TaxTotal;
            }
            set
            {
                if (_TaxTotal != value)
                {
                    OnTaxTotalChanging(value);
                    ReportPropertyChanging("TaxTotal");
                    _TaxTotal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxTotal");
                    OnTaxTotalChanged();
                }
            }
        }
        private global::System.Decimal _TaxTotal;
        partial void OnTaxTotalChanging(global::System.Decimal value);
        partial void OnTaxTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SubTotal
        {
            get
            {
                return _SubTotal;
            }
            set
            {
                if (_SubTotal != value)
                {
                    OnSubTotalChanging(value);
                    ReportPropertyChanging("SubTotal");
                    _SubTotal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubTotal");
                    OnSubTotalChanged();
                }
            }
        }
        private global::System.Decimal _SubTotal;
        partial void OnSubTotalChanging(global::System.Decimal value);
        partial void OnSubTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Total
        {
            get
            {
                return _Total;
            }
            set
            {
                if (_Total != value)
                {
                    OnTotalChanging(value);
                    ReportPropertyChanging("Total");
                    _Total = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Total");
                    OnTotalChanged();
                }
            }
        }
        private global::System.Decimal _Total;
        partial void OnTotalChanging(global::System.Decimal value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PaidAmount
        {
            get
            {
                return _PaidAmount;
            }
            set
            {
                if (_PaidAmount != value)
                {
                    OnPaidAmountChanging(value);
                    ReportPropertyChanging("PaidAmount");
                    _PaidAmount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaidAmount");
                    OnPaidAmountChanged();
                }
            }
        }
        private global::System.Decimal _PaidAmount;
        partial void OnPaidAmountChanging(global::System.Decimal value);
        partial void OnPaidAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaymentID
        {
            get
            {
                return _PaymentID;
            }
            set
            {
                if (_PaymentID != value)
                {
                    OnPaymentIDChanging(value);
                    ReportPropertyChanging("PaymentID");
                    _PaymentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaymentID");
                    OnPaymentIDChanged();
                }
            }
        }
        private global::System.Int32 _PaymentID;
        partial void OnPaymentIDChanging(global::System.Int32 value);
        partial void OnPaymentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CoupTotal
        {
            get
            {
                return _CoupTotal;
            }
            set
            {
                if (_CoupTotal != value)
                {
                    OnCoupTotalChanging(value);
                    ReportPropertyChanging("CoupTotal");
                    _CoupTotal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CoupTotal");
                    OnCoupTotalChanged();
                }
            }
        }
        private global::System.Decimal _CoupTotal;
        partial void OnCoupTotalChanging(global::System.Decimal value);
        partial void OnCoupTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal DiscTotal
        {
            get
            {
                return _DiscTotal;
            }
            set
            {
                if (_DiscTotal != value)
                {
                    OnDiscTotalChanging(value);
                    ReportPropertyChanging("DiscTotal");
                    _DiscTotal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DiscTotal");
                    OnDiscTotalChanged();
                }
            }
        }
        private global::System.Decimal _DiscTotal;
        partial void OnDiscTotalChanging(global::System.Decimal value);
        partial void OnDiscTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                if (_Deleted != value)
                {
                    OnDeletedChanging(value);
                    ReportPropertyChanging("Deleted");
                    _Deleted = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Deleted");
                    OnDeletedChanged();
                }
            }
        }
        private global::System.Boolean _Deleted;
        partial void OnDeletedChanging(global::System.Boolean value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CoupDiscable
        {
            get
            {
                return _CoupDiscable;
            }
            set
            {
                if (_CoupDiscable != value)
                {
                    OnCoupDiscableChanging(value);
                    ReportPropertyChanging("CoupDiscable");
                    _CoupDiscable = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CoupDiscable");
                    OnCoupDiscableChanged();
                }
            }
        }
        private global::System.Decimal _CoupDiscable;
        partial void OnCoupDiscableChanging(global::System.Decimal value);
        partial void OnCoupDiscableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SrvFeeable
        {
            get
            {
                return _SrvFeeable;
            }
            set
            {
                if (_SrvFeeable != value)
                {
                    OnSrvFeeableChanging(value);
                    ReportPropertyChanging("SrvFeeable");
                    _SrvFeeable = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SrvFeeable");
                    OnSrvFeeableChanged();
                }
            }
        }
        private global::System.Decimal _SrvFeeable;
        partial void OnSrvFeeableChanging(global::System.Decimal value);
        partial void OnSrvFeeableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SrvFeeTotal
        {
            get
            {
                return _SrvFeeTotal;
            }
            set
            {
                if (_SrvFeeTotal != value)
                {
                    OnSrvFeeTotalChanging(value);
                    ReportPropertyChanging("SrvFeeTotal");
                    _SrvFeeTotal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SrvFeeTotal");
                    OnSrvFeeTotalChanged();
                }
            }
        }
        private global::System.Decimal _SrvFeeTotal;
        partial void OnSrvFeeTotalChanging(global::System.Decimal value);
        partial void OnSrvFeeTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PaymentDate
        {
            get
            {
                return _PaymentDate;
            }
            set
            {
                OnPaymentDateChanging(value);
                ReportPropertyChanging("PaymentDate");
                _PaymentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaymentDate");
                OnPaymentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PaymentDate;
        partial void OnPaymentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPaymentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HotelRoom
        {
            get
            {
                return _HotelRoom;
            }
            set
            {
                OnHotelRoomChanging(value);
                ReportPropertyChanging("HotelRoom");
                _HotelRoom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HotelRoom");
                OnHotelRoomChanged();
            }
        }
        private global::System.String _HotelRoom;
        partial void OnHotelRoomChanging(global::System.String value);
        partial void OnHotelRoomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuestName
        {
            get
            {
                return _GuestName;
            }
            set
            {
                OnGuestNameChanging(value);
                ReportPropertyChanging("GuestName");
                _GuestName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuestName");
                OnGuestNameChanged();
            }
        }
        private global::System.String _GuestName;
        partial void OnGuestNameChanging(global::System.String value);
        partial void OnGuestNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ValetTicketID
        {
            get
            {
                return _ValetTicketID;
            }
            set
            {
                if (_ValetTicketID != value)
                {
                    OnValetTicketIDChanging(value);
                    ReportPropertyChanging("ValetTicketID");
                    _ValetTicketID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ValetTicketID");
                    OnValetTicketIDChanged();
                }
            }
        }
        private global::System.Int32 _ValetTicketID;
        partial void OnValetTicketIDChanging(global::System.Int32 value);
        partial void OnValetTicketIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BillCustomerID
        {
            get
            {
                return _BillCustomerID;
            }
            set
            {
                if (_BillCustomerID != value)
                {
                    OnBillCustomerIDChanging(value);
                    ReportPropertyChanging("BillCustomerID");
                    _BillCustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BillCustomerID");
                    OnBillCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _BillCustomerID;
        partial void OnBillCustomerIDChanging(global::System.Int32 value);
        partial void OnBillCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tax2ID
        {
            get
            {
                return _Tax2ID;
            }
            set
            {
                if (_Tax2ID != value)
                {
                    OnTax2IDChanging(value);
                    ReportPropertyChanging("Tax2ID");
                    _Tax2ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Tax2ID");
                    OnTax2IDChanged();
                }
            }
        }
        private global::System.Int32 _Tax2ID;
        partial void OnTax2IDChanging(global::System.Int32 value);
        partial void OnTax2IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tax3ID
        {
            get
            {
                return _Tax3ID;
            }
            set
            {
                if (_Tax3ID != value)
                {
                    OnTax3IDChanging(value);
                    ReportPropertyChanging("Tax3ID");
                    _Tax3ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Tax3ID");
                    OnTax3IDChanged();
                }
            }
        }
        private global::System.Int32 _Tax3ID;
        partial void OnTax3IDChanging(global::System.Int32 value);
        partial void OnTax3IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Taxable1
        {
            get
            {
                return _Taxable1;
            }
            set
            {
                if (_Taxable1 != value)
                {
                    OnTaxable1Changing(value);
                    ReportPropertyChanging("Taxable1");
                    _Taxable1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Taxable1");
                    OnTaxable1Changed();
                }
            }
        }
        private global::System.Decimal _Taxable1;
        partial void OnTaxable1Changing(global::System.Decimal value);
        partial void OnTaxable1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Taxable2
        {
            get
            {
                return _Taxable2;
            }
            set
            {
                if (_Taxable2 != value)
                {
                    OnTaxable2Changing(value);
                    ReportPropertyChanging("Taxable2");
                    _Taxable2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Taxable2");
                    OnTaxable2Changed();
                }
            }
        }
        private global::System.Decimal _Taxable2;
        partial void OnTaxable2Changing(global::System.Decimal value);
        partial void OnTaxable2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Taxable3
        {
            get
            {
                return _Taxable3;
            }
            set
            {
                if (_Taxable3 != value)
                {
                    OnTaxable3Changing(value);
                    ReportPropertyChanging("Taxable3");
                    _Taxable3 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Taxable3");
                    OnTaxable3Changed();
                }
            }
        }
        private global::System.Decimal _Taxable3;
        partial void OnTaxable3Changing(global::System.Decimal value);
        partial void OnTaxable3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TaxTotal1
        {
            get
            {
                return _TaxTotal1;
            }
            set
            {
                if (_TaxTotal1 != value)
                {
                    OnTaxTotal1Changing(value);
                    ReportPropertyChanging("TaxTotal1");
                    _TaxTotal1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxTotal1");
                    OnTaxTotal1Changed();
                }
            }
        }
        private global::System.Decimal _TaxTotal1;
        partial void OnTaxTotal1Changing(global::System.Decimal value);
        partial void OnTaxTotal1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TaxTotal2
        {
            get
            {
                return _TaxTotal2;
            }
            set
            {
                if (_TaxTotal2 != value)
                {
                    OnTaxTotal2Changing(value);
                    ReportPropertyChanging("TaxTotal2");
                    _TaxTotal2 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxTotal2");
                    OnTaxTotal2Changed();
                }
            }
        }
        private global::System.Decimal _TaxTotal2;
        partial void OnTaxTotal2Changing(global::System.Decimal value);
        partial void OnTaxTotal2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TaxTotal3
        {
            get
            {
                return _TaxTotal3;
            }
            set
            {
                if (_TaxTotal3 != value)
                {
                    OnTaxTotal3Changing(value);
                    ReportPropertyChanging("TaxTotal3");
                    _TaxTotal3 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxTotal3");
                    OnTaxTotal3Changed();
                }
            }
        }
        private global::System.Decimal _TaxTotal3;
        partial void OnTaxTotal3Changing(global::System.Decimal value);
        partial void OnTaxTotal3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal OriginalTotal
        {
            get
            {
                return _OriginalTotal;
            }
            set
            {
                if (_OriginalTotal != value)
                {
                    OnOriginalTotalChanging(value);
                    ReportPropertyChanging("OriginalTotal");
                    _OriginalTotal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OriginalTotal");
                    OnOriginalTotalChanged();
                }
            }
        }
        private global::System.Decimal _OriginalTotal;
        partial void OnOriginalTotalChanging(global::System.Decimal value);
        partial void OnOriginalTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRedo
        {
            get
            {
                return _IsRedo;
            }
            set
            {
                if (_IsRedo != value)
                {
                    OnIsRedoChanging(value);
                    ReportPropertyChanging("IsRedo");
                    _IsRedo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsRedo");
                    OnIsRedoChanged();
                }
            }
        }
        private global::System.Boolean _IsRedo;
        partial void OnIsRedoChanging(global::System.Boolean value);
        partial void OnIsRedoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSplit
        {
            get
            {
                return _IsSplit;
            }
            set
            {
                if (_IsSplit != value)
                {
                    OnIsSplitChanging(value);
                    ReportPropertyChanging("IsSplit");
                    _IsSplit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IsSplit");
                    OnIsSplitChanged();
                }
            }
        }
        private global::System.Boolean _IsSplit;
        partial void OnIsSplitChanging(global::System.Boolean value);
        partial void OnIsSplitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TaxAuthorityID
        {
            get
            {
                return _TaxAuthorityID;
            }
            set
            {
                if (_TaxAuthorityID != value)
                {
                    OnTaxAuthorityIDChanging(value);
                    ReportPropertyChanging("TaxAuthorityID");
                    _TaxAuthorityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxAuthorityID");
                    OnTaxAuthorityIDChanged();
                }
            }
        }
        private global::System.Int32 _TaxAuthorityID;
        partial void OnTaxAuthorityIDChanging(global::System.Int32 value);
        partial void OnTaxAuthorityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BaggerMemo
        {
            get
            {
                return _BaggerMemo;
            }
            set
            {
                OnBaggerMemoChanging(value);
                ReportPropertyChanging("BaggerMemo");
                _BaggerMemo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BaggerMemo");
                OnBaggerMemoChanged();
            }
        }
        private global::System.String _BaggerMemo;
        partial void OnBaggerMemoChanging(global::System.String value);
        partial void OnBaggerMemoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PayCode
        {
            get
            {
                return _PayCode;
            }
            set
            {
                if (_PayCode != value)
                {
                    OnPayCodeChanging(value);
                    ReportPropertyChanging("PayCode");
                    _PayCode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PayCode");
                    OnPayCodeChanged();
                }
            }
        }
        private global::System.Int32 _PayCode;
        partial void OnPayCodeChanging(global::System.Int32 value);
        partial void OnPayCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AssemblyDate
        {
            get
            {
                return _AssemblyDate;
            }
            set
            {
                OnAssemblyDateChanging(value);
                ReportPropertyChanging("AssemblyDate");
                _AssemblyDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AssemblyDate");
                OnAssemblyDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _AssemblyDate;
        partial void OnAssemblyDateChanging(Nullable<global::System.DateTime> value);
        partial void OnAssemblyDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MarkInDate
        {
            get
            {
                return _MarkInDate;
            }
            set
            {
                OnMarkInDateChanging(value);
                ReportPropertyChanging("MarkInDate");
                _MarkInDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarkInDate");
                OnMarkInDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MarkInDate;
        partial void OnMarkInDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMarkInDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MarkInEmpID
        {
            get
            {
                return _MarkInEmpID;
            }
            set
            {
                if (_MarkInEmpID != value)
                {
                    OnMarkInEmpIDChanging(value);
                    ReportPropertyChanging("MarkInEmpID");
                    _MarkInEmpID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MarkInEmpID");
                    OnMarkInEmpIDChanged();
                }
            }
        }
        private global::System.Int32 _MarkInEmpID;
        partial void OnMarkInEmpIDChanging(global::System.Int32 value);
        partial void OnMarkInEmpIDChanged();

        #endregion

    
    }

    #endregion

    
}
