//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BCSModel", "FK_Bins_Categories", "Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(OnTheSpot.EFStuff.Category), "Bins", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnTheSpot.EFStuff.Bin), true)]
[assembly: EdmRelationshipAttribute("BCSModel", "FK_Items_Categories", "Category", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(OnTheSpot.EFStuff.Category), "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(OnTheSpot.EFStuff.Item), true)]

#endregion

namespace OnTheSpot.EFStuff
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bin> Bins
        {
            get
            {
                if ((_Bins == null))
                {
                    _Bins = base.CreateObjectSet<Bin>("Bins");
                }
                return _Bins;
            }
        }
        private ObjectSet<Bin> _Bins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GSS> GSSes
        {
            get
            {
                if ((_GSSes == null))
                {
                    _GSSes = base.CreateObjectSet<GSS>("GSSes");
                }
                return _GSSes;
            }
        }
        private ObjectSet<GSS> _GSSes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Printer> Printers
        {
            get
            {
                if ((_Printers == null))
                {
                    _Printers = base.CreateObjectSet<Printer>("Printers");
                }
                return _Printers;
            }
        }
        private ObjectSet<Printer> _Printers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Configuration> Configurations
        {
            get
            {
                if ((_Configurations == null))
                {
                    _Configurations = base.CreateObjectSet<Configuration>("Configurations");
                }
                return _Configurations;
            }
        }
        private ObjectSet<Configuration> _Configurations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QCSInfo> QCSInfoes
        {
            get
            {
                if ((_QCSInfoes == null))
                {
                    _QCSInfoes = base.CreateObjectSet<QCSInfo>("QCSInfoes");
                }
                return _QCSInfoes;
            }
        }
        private ObjectSet<QCSInfo> _QCSInfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBins(Bin bin)
        {
            base.AddObject("Bins", bin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GSSes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGSSes(GSS gSS)
        {
            base.AddObject("GSSes", gSS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Printers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrinters(Printer printer)
        {
            base.AddObject("Printers", printer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Configurations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigurations(Configuration configuration)
        {
            base.AddObject("Configurations", configuration);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QCSInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQCSInfoes(QCSInfo qCSInfo)
        {
            base.AddObject("QCSInfoes", qCSInfo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCSModel", Name="Bin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bin object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="phigidSlot">Initial value of the PhigidSlot property.</param>
        public static Bin CreateBin(global::System.Int32 id, global::System.Int32 category, global::System.Int32 phigidSlot)
        {
            Bin bin = new Bin();
            bin.ID = id;
            bin.Category = category;
            bin.PhigidSlot = phigidSlot;
            return bin;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BarCode
        {
            get
            {
                return _BarCode;
            }
            set
            {
                OnBarCodeChanging(value);
                ReportPropertyChanging("BarCode");
                _BarCode = StructuralObject.SetValidValue(value, true, "BarCode");
                ReportPropertyChanged("BarCode");
                OnBarCodeChanged();
            }
        }
        private global::System.String _BarCode;
        partial void OnBarCodeChanging(global::System.String value);
        partial void OnBarCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value, true, "Weight");
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private global::System.String _Weight;
        partial void OnWeightChanging(global::System.String value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaxWeight
        {
            get
            {
                return _MaxWeight;
            }
            set
            {
                OnMaxWeightChanging(value);
                ReportPropertyChanging("MaxWeight");
                _MaxWeight = StructuralObject.SetValidValue(value, true, "MaxWeight");
                ReportPropertyChanged("MaxWeight");
                OnMaxWeightChanged();
            }
        }
        private global::System.String _MaxWeight;
        partial void OnMaxWeightChanging(global::System.String value);
        partial void OnMaxWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, "Category");
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.Int32 _Category;
        partial void OnCategoryChanging(global::System.Int32 value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhigidSlot
        {
            get
            {
                return _PhigidSlot;
            }
            set
            {
                OnPhigidSlotChanging(value);
                ReportPropertyChanging("PhigidSlot");
                _PhigidSlot = StructuralObject.SetValidValue(value, "PhigidSlot");
                ReportPropertyChanged("PhigidSlot");
                OnPhigidSlotChanged();
            }
        }
        private global::System.Int32 _PhigidSlot;
        partial void OnPhigidSlotChanging(global::System.Int32 value);
        partial void OnPhigidSlotChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCSModel", "FK_Bins_Categories", "Categories")]
        public Category Category1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("BCSModel.FK_Bins_Categories", "Categories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("BCSModel.FK_Bins_Categories", "Categories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> Category1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("BCSModel.FK_Bins_Categories", "Categories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("BCSModel.FK_Bins_Categories", "Categories", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCSModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Category CreateCategory(global::System.Int32 id)
        {
            Category category = new Category();
            category.ID = id;
            return category;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCSModel", "FK_Bins_Categories", "Bins")]
        public EntityCollection<Bin> Bins
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bin>("BCSModel.FK_Bins_Categories", "Bins");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bin>("BCSModel.FK_Bins_Categories", "Bins", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCSModel", "FK_Items_Categories", "Item")]
        public EntityCollection<Item> Items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Item>("BCSModel.FK_Items_Categories", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Item>("BCSModel.FK_Items_Categories", "Item", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCSModel", Name="Configuration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Configuration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Configuration object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pOSWindow">Initial value of the POSWindow property.</param>
        public static Configuration CreateConfiguration(global::System.Int32 id, global::System.String pOSWindow)
        {
            Configuration configuration = new Configuration();
            configuration.Id = id;
            configuration.POSWindow = pOSWindow;
            return configuration;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String POSWindow
        {
            get
            {
                return _POSWindow;
            }
            set
            {
                OnPOSWindowChanging(value);
                ReportPropertyChanging("POSWindow");
                _POSWindow = StructuralObject.SetValidValue(value, false, "POSWindow");
                ReportPropertyChanged("POSWindow");
                OnPOSWindowChanged();
            }
        }
        private global::System.String _POSWindow;
        partial void OnPOSWindowChanging(global::System.String value);
        partial void OnPOSWindowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShowPass
        {
            get
            {
                return _ShowPass;
            }
            set
            {
                OnShowPassChanging(value);
                ReportPropertyChanging("ShowPass");
                _ShowPass = StructuralObject.SetValidValue(value, "ShowPass");
                ReportPropertyChanged("ShowPass");
                OnShowPassChanged();
            }
        }
        private Nullable<global::System.Int32> _ShowPass;
        partial void OnShowPassChanging(Nullable<global::System.Int32> value);
        partial void OnShowPassChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCSModel", Name="GSS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GSS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GSS object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="barcode">Initial value of the barcode property.</param>
        /// <param name="bin">Initial value of the bin property.</param>
        /// <param name="time">Initial value of the time property.</param>
        public static GSS CreateGSS(global::System.Int32 id, global::System.String barcode, global::System.Int32 bin, global::System.DateTime time)
        {
            GSS gSS = new GSS();
            gSS.id = id;
            gSS.barcode = barcode;
            gSS.bin = bin;
            gSS.time = time;
            return gSS;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String barcode
        {
            get
            {
                return _barcode;
            }
            set
            {
                OnbarcodeChanging(value);
                ReportPropertyChanging("barcode");
                _barcode = StructuralObject.SetValidValue(value, false, "barcode");
                ReportPropertyChanged("barcode");
                OnbarcodeChanged();
            }
        }
        private global::System.String _barcode;
        partial void OnbarcodeChanging(global::System.String value);
        partial void OnbarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bin
        {
            get
            {
                return _bin;
            }
            set
            {
                OnbinChanging(value);
                ReportPropertyChanging("bin");
                _bin = StructuralObject.SetValidValue(value, "bin");
                ReportPropertyChanged("bin");
                OnbinChanged();
            }
        }
        private global::System.Int32 _bin;
        partial void OnbinChanging(global::System.Int32 value);
        partial void OnbinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value, "time");
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.DateTime _time;
        partial void OntimeChanging(global::System.DateTime value);
        partial void OntimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String temp
        {
            get
            {
                return _temp;
            }
            set
            {
                OntempChanging(value);
                ReportPropertyChanging("temp");
                _temp = StructuralObject.SetValidValue(value, true, "temp");
                ReportPropertyChanged("temp");
                OntempChanged();
            }
        }
        private global::System.String _temp;
        partial void OntempChanging(global::System.String value);
        partial void OntempChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String temp1
        {
            get
            {
                return _temp1;
            }
            set
            {
                Ontemp1Changing(value);
                ReportPropertyChanging("temp1");
                _temp1 = StructuralObject.SetValidValue(value, true, "temp1");
                ReportPropertyChanged("temp1");
                Ontemp1Changed();
            }
        }
        private global::System.String _temp1;
        partial void Ontemp1Changing(global::System.String value);
        partial void Ontemp1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String temp2
        {
            get
            {
                return _temp2;
            }
            set
            {
                Ontemp2Changing(value);
                ReportPropertyChanging("temp2");
                _temp2 = StructuralObject.SetValidValue(value, true, "temp2");
                ReportPropertyChanged("temp2");
                Ontemp2Changed();
            }
        }
        private global::System.String _temp2;
        partial void Ontemp2Changing(global::System.String value);
        partial void Ontemp2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String temp3
        {
            get
            {
                return _temp3;
            }
            set
            {
                Ontemp3Changing(value);
                ReportPropertyChanging("temp3");
                _temp3 = StructuralObject.SetValidValue(value, true, "temp3");
                ReportPropertyChanged("temp3");
                Ontemp3Changed();
            }
        }
        private global::System.String _temp3;
        partial void Ontemp3Changing(global::System.String value);
        partial void Ontemp3Changed();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCSModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Item CreateItem(global::System.Int32 id)
        {
            Item item = new Item();
            item.ID = id;
            return item;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CustID
        {
            get
            {
                return _CustID;
            }
            set
            {
                OnCustIDChanging(value);
                ReportPropertyChanging("CustID");
                _CustID = StructuralObject.SetValidValue(value, "CustID");
                ReportPropertyChanged("CustID");
                OnCustIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CustID;
        partial void OnCustIDChanging(Nullable<global::System.Int32> value);
        partial void OnCustIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BarCode
        {
            get
            {
                return _BarCode;
            }
            set
            {
                OnBarCodeChanging(value);
                ReportPropertyChanging("BarCode");
                _BarCode = StructuralObject.SetValidValue(value, true, "BarCode");
                ReportPropertyChanged("BarCode");
                OnBarCodeChanged();
            }
        }
        private global::System.String _BarCode;
        partial void OnBarCodeChanging(global::System.String value);
        partial void OnBarCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true, "State");
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CatID
        {
            get
            {
                return _CatID;
            }
            set
            {
                OnCatIDChanging(value);
                ReportPropertyChanging("CatID");
                _CatID = StructuralObject.SetValidValue(value, "CatID");
                ReportPropertyChanged("CatID");
                OnCatIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CatID;
        partial void OnCatIDChanging(Nullable<global::System.Int32> value);
        partial void OnCatIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value, "CreateDate");
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true, "Note");
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String picture
        {
            get
            {
                return _picture;
            }
            set
            {
                OnpictureChanging(value);
                ReportPropertyChanging("picture");
                _picture = StructuralObject.SetValidValue(value, true, "picture");
                ReportPropertyChanged("picture");
                OnpictureChanged();
            }
        }
        private global::System.String _picture;
        partial void OnpictureChanging(global::System.String value);
        partial void OnpictureChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BCSModel", "FK_Items_Categories", "Category")]
        public Category Category
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("BCSModel.FK_Items_Categories", "Category").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("BCSModel.FK_Items_Categories", "Category").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Category> CategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Category>("BCSModel.FK_Items_Categories", "Category");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Category>("BCSModel.FK_Items_Categories", "Category", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCSModel", Name="Printer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Printer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Printer object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="storename">Initial value of the storename property.</param>
        /// <param name="printerName">Initial value of the printerName property.</param>
        public static Printer CreatePrinter(global::System.Int32 id, global::System.String storename, global::System.String printerName)
        {
            Printer printer = new Printer();
            printer.id = id;
            printer.storename = storename;
            printer.printerName = printerName;
            return printer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String storename
        {
            get
            {
                return _storename;
            }
            set
            {
                OnstorenameChanging(value);
                ReportPropertyChanging("storename");
                _storename = StructuralObject.SetValidValue(value, false, "storename");
                ReportPropertyChanged("storename");
                OnstorenameChanged();
            }
        }
        private global::System.String _storename;
        partial void OnstorenameChanging(global::System.String value);
        partial void OnstorenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String printerName
        {
            get
            {
                return _printerName;
            }
            set
            {
                OnprinterNameChanging(value);
                ReportPropertyChanging("printerName");
                _printerName = StructuralObject.SetValidValue(value, false, "printerName");
                ReportPropertyChanged("printerName");
                OnprinterNameChanged();
            }
        }
        private global::System.String _printerName;
        partial void OnprinterNameChanging(global::System.String value);
        partial void OnprinterNameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BCSModel", Name="QCSInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QCSInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QCSInfo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="heatSeal">Initial value of the HeatSeal property.</param>
        /// <param name="bin">Initial value of the Bin property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        public static QCSInfo CreateQCSInfo(global::System.Int32 id, global::System.String heatSeal, global::System.String bin, global::System.DateTime time)
        {
            QCSInfo qCSInfo = new QCSInfo();
            qCSInfo.id = id;
            qCSInfo.HeatSeal = heatSeal;
            qCSInfo.Bin = bin;
            qCSInfo.Time = time;
            return qCSInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HeatSeal
        {
            get
            {
                return _HeatSeal;
            }
            set
            {
                OnHeatSealChanging(value);
                ReportPropertyChanging("HeatSeal");
                _HeatSeal = StructuralObject.SetValidValue(value, false, "HeatSeal");
                ReportPropertyChanged("HeatSeal");
                OnHeatSealChanged();
            }
        }
        private global::System.String _HeatSeal;
        partial void OnHeatSealChanging(global::System.String value);
        partial void OnHeatSealChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bin
        {
            get
            {
                return _Bin;
            }
            set
            {
                OnBinChanging(value);
                ReportPropertyChanging("Bin");
                _Bin = StructuralObject.SetValidValue(value, false, "Bin");
                ReportPropertyChanged("Bin");
                OnBinChanged();
            }
        }
        private global::System.String _Bin;
        partial void OnBinChanging(global::System.String value);
        partial void OnBinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, "Time");
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();

        #endregion

    }

    #endregion

}
